import 'package:flutter/material.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/Generated1732PMWidget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedIPhoneSE1Widget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedIcbaselinecardgiftcardWidget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedEntyposignalWidget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedIcbaselinecardgiftcardWidget2.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedFooderlichWidget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedCard2Widget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedIcbaselinecardgiftcardWidget1.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedCard3Widget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid1widget/generated/GeneratedCard1Widget.dart';

/* Frame Android - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 320.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedEntyposignalWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 568.0,
                child: GeneratedIPhoneSE1Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 358.0,
                height: 83.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 83.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 16.000165939331055,
                child: GeneratedVectorWidget(),
              ),
              Positioned(
                left: 315.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 15.0,
                child: GeneratedGroupWidget(),
              ),
              Positioned(
                left: 157.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 14.0,
                child: Generated1732PMWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 19.0,
                child: GeneratedFooderlichWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 19.0,
                child: GeneratedCard1Widget(),
              ),
              Positioned(
                left: 163.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 19.0,
                child: GeneratedCard2Widget(),
              ),
              Positioned(
                left: 280.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselinecardgiftcardWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselinecardgiftcardWidget1(),
              ),
              Positioned(
                left: 167.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselinecardgiftcardWidget2(),
              ),
              Positioned(
                left: 275.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 19.0,
                child: GeneratedCard3Widget(),
              )
            ]),
      ),
    ));
  }
}
