import 'package:flutter/material.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedGroupWidget1.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedCard2Widget1.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/Generated1732PMWidget1.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedEntyposignalWidget1.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedIPhoneSE2Widget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedFooderlichWidget1.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedIcbaselinecardgiftcardWidget4.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedIcbaselinecardgiftcardWidget3.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedIcbaselinecardgiftcardWidget5.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedBibatteryfullWidget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedCard3Widget1.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedVectorWidget10.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid2widget/generated/GeneratedCard1Widget1.dart';

/* Frame Android - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedBibatteryfullWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedEntyposignalWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 568.0,
                child: GeneratedIPhoneSE2Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 358.0,
                height: 83.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 52.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 19.0,
                child: GeneratedCard1Widget1(),
              ),
              Positioned(
                left: 163.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 19.0,
                child: GeneratedCard2Widget1(),
              ),
              Positioned(
                left: 280.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselinecardgiftcardWidget3(),
              ),
              Positioned(
                left: 54.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselinecardgiftcardWidget4(),
              ),
              Positioned(
                left: 167.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselinecardgiftcardWidget5(),
              ),
              Positioned(
                left: 275.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 19.0,
                child: GeneratedCard3Widget1(),
              ),
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 83.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 16.000165939331055,
                child: GeneratedVectorWidget10(),
              ),
              Positioned(
                left: 315.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 15.0,
                child: GeneratedGroupWidget1(),
              ),
              Positioned(
                left: 157.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 14.0,
                child: Generated1732PMWidget1(),
              ),
              Positioned(
                left: 156.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 19.0,
                child: GeneratedFooderlichWidget1(),
              )
            ]),
      ),
    ));
  }
}
