import 'package:flutter/material.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedIcbaselinecardgiftcardWidget9.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedVectorWidget26.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedGroupWidget6.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedCard3Widget3.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedCard2Widget3.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/Generated1732PMWidget3.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedIcbaselinecardgiftcardWidget11.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedIcbaselinecardgiftcardWidget10.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedRectangle4Widget3.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedIPhoneSE3Widget.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedFooderlichWidget3.dart';
import 'package:flutterapp/resepbysintiaapp/generatedandroid3widget/generated/GeneratedCard1Widget3.dart';

/* Frame Android - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 568.0,
                child: GeneratedIPhoneSE3Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 83.0,
                child: GeneratedRectangle4Widget3(),
              ),
              Positioned(
                left: 10.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 16.000165939331055,
                child: GeneratedVectorWidget26(),
              ),
              Positioned(
                left: 315.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 15.0,
                child: GeneratedGroupWidget6(),
              ),
              Positioned(
                left: 157.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 14.0,
                child: Generated1732PMWidget3(),
              ),
              Positioned(
                left: 156.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 19.0,
                child: GeneratedFooderlichWidget3(),
              ),
              Positioned(
                left: 1.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 358.0,
                height: 83.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 52.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 19.0,
                child: GeneratedCard1Widget3(),
              ),
              Positioned(
                left: 163.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 19.0,
                child: GeneratedCard2Widget3(),
              ),
              Positioned(
                left: 280.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselinecardgiftcardWidget9(),
              ),
              Positioned(
                left: 54.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselinecardgiftcardWidget10(),
              ),
              Positioned(
                left: 167.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselinecardgiftcardWidget11(),
              ),
              Positioned(
                left: 275.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 19.0,
                child: GeneratedCard3Widget3(),
              )
            ]),
      ),
    ));
  }
}
